services:

  # The Brain: Elasticsearch
  aa-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: aa-elasticsearch
    environment:
      - node.name=aa-elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false # Set to true later for production hardening
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - arena-net

  # The Collector: Logstash
  aa-logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: aa-logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    depends_on:
      - aa-elasticsearch
    networks:
      - arena-net

  # The Face: Kibana
  aa-kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: aa-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://aa-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - aa-elasticsearch
    networks:
      - arena-net

networks:
  arena-net:
    driver: bridge

volumes:
  esdata:
    driver: local