services:

  # The Brain: Elasticsearch
  af-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: af-elasticsearch
    environment:
      - node.name=af-elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false # Set to true later for production hardening
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - forge-net

  # The Collector: Logstash
  af-logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: af-logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    depends_on:
      - af-elasticsearch
    networks:
      - forge-net

  # The Face: Kibana
  af-kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: af-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://af-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - af-elasticsearch
    networks:
      - forge-net

networks:
  forge-net:
    driver: bridge

volumes:
  esdata:
    driver: local