winlogbeat.event_logs:
  - name: Security
  - name: Microsoft-Windows-Sysmon/Operational
  - name: Microsoft-Windows-PowerShell/Operational
    event_id: 4104 # Captures Script Blocks

output.logstash:
  hosts: ["<SENTINEL-IP>:5044"]

logging.level: info
logging.to_files: true